apiVersion: v1
kind: Service
metadata:
  name: intens-demo
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: intens-demo
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
      nodePort: 30008

